language: java
jdk:
  - oraclejdk8
sudo: required
env:
  global:
    secure: "ap70+WSYdeaM1iIG3DhVvlsBClNtn+uFZleJ0Rizn4qo9lqLSbVuxuyCXPCoFgHh5u8Lo0BDhRZ0qptHJKQuzf5An2S7QEqLA+Q4wl8oCUVGAAz3hQDxSFA/qp1RMx+F0DRR+vekN0ZEZk4yMuOpeCpWK5cvMO1x2L8kKjBR5zB0SaX6F7FNvat7neSpAOKK6P1aw5eEDr+0jl0ttpZ1S98ZJouwYxXyCVCzrxEr0ZaWoFQ11T2UalS6d8cxOi7NlXMJzsdlO+MDFHlUmUt+KF50+xnwx5Vrtp4X1o7UVW1f0AmYPoRouwCauR0YeMQI3wEfRwhsPdiTiMwilASKRo9bj6vwdWXT/2Rp3+FoEm4vwYIbnJP6uI7qpdh+bYLcHZgMgNDLlaGfHCUPL8Z3HSR085nQVrfVTIAR+WF3hZAZfgsJ9gYsS8RfxODNUr3xRat8sdx0qeBfRaftB1HT9Rq5IrV5qtRGQUNY9InpL/oRZfQ9zxi9pZSGNsaqJqi8S1g1vB5pyAWuiyRuDYnhnw5HatLv1VFcNWR5yqcKwO8B/PymUWVy3uU7rg2YcdKVSNEOXqqTNEYbaVweqmJWoAjBXrhnKGqIxdjNK8bTrce9B99zXAv48rSSSMHNZ66AUJ6Vt/ogmI9emvcwqXA58oTy5xhcHzpTIciJbECvc6o="
services:
  - docker
script: ./integration-test-build/build-and-run.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.cache/docker/'
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
