language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
script: ./integration-test-build/build-and-run.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
